// js/admin.js
document.addEventListener('DOMContentLoaded', async () => {
    const session = await checkSession(); // from auth.js
        if (session.authenticated && session.role === 'admin') {
                document.getElementById('userName').textContent = session.full_name;
                        loadUsers();
                            } else {
                                    window.location.href = 'index.html';
                                        }

                                            document.getElementById('logoutBtn').addEventListener('click', logout);
                                            });

                                            async function loadUsers() {
                                                const res = await fetch('api/admin.php?action=list');
                                                    const data = await res.json();
                                                        if (data.status === 'success') {
                                                                const tbody = document.querySelector('#usersTable tbody');
                                                                        tbody.innerHTML = data.users.map(u => `
                                                                                    <tr>
                                                                                                    <td>${escapeHtml(u.username)}</td>
                                                                                                                    <td>${escapeHtml(u.full_name)}</td>
                                                                                                                                    <td>${u.role}</td>
                                                                                                                                                    <td>${escapeHtml(u.email)}</td>
                                                                                                                                                                    <td><span class="badge badge-${u.status === 'active' ? 'success' : 'danger'}">${u.status}</span></td>
                                                                                                                                                                                    <td>
                                                                                                                                                                                                        ${u.role !== 'admin' ? `<button class="btn-outline btn-sm" onclick="toggleStatus(${u.user_id}, '${u.status}')">${u.status === 'active' ? 'Deactivate' : 'Activate'}</button>` : ''}
                                                                                                                                                                                                                        </td>
                                                                                                                                                                                                                                    </tr>
                                                                                                                                                                                                                                            `).join('');
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                function escapeHtml(text) {
                                                                                                                                                                                                                                                    const div = document.createElement('div');
                                                                                                                                                                                                                                                        div.textContent = text;
                                                                                                                                                                                                                                                            return div.innerHTML;
                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                            function openCreateUserModal() {
                                                                                                                                                                                                                                                                document.getElementById('createUserModal').classList.remove('hidden');
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                function closeModal() {
                                                                                                                                                                                                                                                                    document.getElementById('createUserModal').classList.add('hidden');
                                                                                                                                                                                                                                                                        document.getElementById('createUserForm').reset();
                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                        document.getElementById('createUserForm').addEventListener('submit', async (e) => {
                                                                                                                                                                                                                                                                            e.preventDefault();
                                                                                                                                                                                                                                                                                const formData = new FormData(e.target);
                                                                                                                                                                                                                                                                                    const data = Object.fromEntries(formData);
                                                                                                                                                                                                                                                                                        const res = await fetch('api/admin.php?action=create', {
                                                                                                                                                                                                                                                                                                method: 'POST',
                                                                                                                                                                                                                                                                                                        headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                                                                                                                                                                body: JSON.stringify(data)
                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                        const result = await res.json();
                                                                                                                                                                                                                                                                                                                            if (result.status === 'success') {
                                                                                                                                                                                                                                                                                                                                    closeModal();
                                                                                                                                                                                                                                                                                                                                            loadUsers();
                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                        alert(result.message);
                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                            async function toggleStatus(userId, currentStatus) {
                                                                                                                                                                                                                                                                                                                                                                const newStatus = currentStatus === 'active' ? 'inactive' : 'active';
                                                                                                                                                                                                                                                                                                                                                                    const res = await fetch('api/admin.php?action=update_status', {
                                                                                                                                                                                                                                                                                                                                                                            method: 'POST',
                                                                                                                                                                                                                                                                                                                                                                                    headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                                                                                                                                                                                                                                            body: JSON.stringify({ user_id: userId, status: newStatus })
                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                    const result = await res.json();
                                                                                                                                                                                                                                                                                                                                                                                                        if (result.status === 'success') loadUsers();
                                                                                                                                                                                                                                                                                                                                                                                                            else alert(result.message);
                                                                                                                                                                                                                                                                                                                                                                                                            }
