// js/importer.js
document.addEventListener('DOMContentLoaded', async () => {
    const session = await checkSession();
        if (!session || session.role !== 'importer') {
                window.location.href = 'index.html';
                        return;
                            }
                                document.getElementById('userName').textContent = session.full_name;
                                    loadProfile();
                                        loadApplications();
                                            loadCropsDropdown();

                                                document.getElementById('applyForm').addEventListener('submit', submitApplication);
                                                    document.getElementById('logoutBtn').addEventListener('click', logout);
                                                    });

                                                    async function loadProfile() {
                                                        const res = await fetch('api/importer.php?action=profile');
                                                            const data = await res.json();
                                                                if (data.status === 'success') {
                                                                        const p = data.profile;
                                                                                document.getElementById('profileBanner').innerHTML = `
                                                                                            <div style="display: flex; flex-wrap: wrap; gap: 2rem;">
                                                                                                            <div><strong>Company:</strong> ${p.company_name}</div>
                                                                                                                            <div><strong>Contact:</strong> ${p.full_name} (${p.email})</div>
                                                                                                                                            <div><strong>Phone:</strong> ${p.phone || 'N/A'}</div>
                                                                                                                                                        </div>
                                                                                                                                                                `;
                                                                                                                                                                    }
                                                                                                                                                                    }

                                                                                                                                                                    async function loadCropsDropdown() {
                                                                                                                                                                        // FIX: Fetch crops from the importer API instead of the farmer API
                                                                                                                                                                            const res = await fetch('api/importer.php?action=crops'); 
                                                                                                                                                                                const data = await res.json();
                                                                                                                                                                                    if (data.status === 'success') {
                                                                                                                                                                                            const select = document.getElementById('cropSelect');
                                                                                                                                                                                                    select.innerHTML = '<option value="">Select Crop</option>' +
                                                                                                                                                                                                                data.crops.map(c => `<option value="${c.crop_id}">${c.crop_name}</option>`).join('');
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                    }

                                                                                                                                                                                                                    async function loadApplications() {
                                                                                                                                                                                                                        const res = await fetch('api/importer.php?action=applications');
                                                                                                                                                                                                                            const data = await res.json();
                                                                                                                                                                                                                                if (data.status === 'success') {
                                                                                                                                                                                                                                        const tbody = document.querySelector('#applicationsTable tbody');
                                                                                                                                                                                                                                                if (data.applications.length === 0) {
                                                                                                                                                                                                                                                            tbody.innerHTML = '<tr><td colspan="6" class="text-center">No applications yet.</td></tr>';
                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                tbody.innerHTML = data.applications.map(app => `
                                                                                                                                                                                                                                                                                                <tr>
                                                                                                                                                                                                                                                                                                                    <td>${app.crop_name}</td>
                                                                                                                                                                                                                                                                                                                                        <td>${app.requested_quantity_tons}</td>
                                                                                                                                                                                                                                                                                                                                                            <td>${app.arrival_date}</td>
                                                                                                                                                                                                                                                                                                                                                                                <td><span class="badge badge-${app.status === 'approved' ? 'success' : (app.status === 'pending' ? 'warning' : 'danger')}">${app.status}</span></td>
                                                                                                                                                                                                                                                                                                                                                                                                    <td>${app.approved_quantity ?? '-'}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                        <td>${app.notes || '-'}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    `).join('');
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                function openApplyModal() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.getElementById('applyModal').classList.remove('hidden');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function closeApplyModal() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById('applyModal').classList.add('hidden');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            document.getElementById('applyForm').reset();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            async function submitApplication(e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                e.preventDefault();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const formData = new FormData(e.target);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const data = Object.fromEntries(formData);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            data.requested_quantity_tons = parseFloat(data.requested_quantity_tons);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const res = await fetch('api/importer.php?action=submit_application', {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        method: 'POST',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        body: JSON.stringify(data)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const result = await res.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (result.status === 'success') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            alert('Application submitted');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    closeApplyModal();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            loadApplications();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        alert(result.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
