// js/auth.js

/**
 * API call helper (simplified for basic use)
  */
  async function apiCall(endpoint, method = 'GET', body = null) {
      const options = {
              method,
                      headers: { 'Content-Type': 'application/json' }
                          };
                              if (body) {
                                      options.body = JSON.stringify(body);
                                          }
                                              const response = await fetch(endpoint, options);
                                                  const data = await response.json();
                                                      if (!response.ok) {
                                                              throw new Error(data.message || 'Request failed');
                                                                  }
                                                                      return data;
                                                                      }

                                                                      /**
                                                                       * Handle login form submission
                                                                        */
                                                                        document.addEventListener('DOMContentLoaded', () => {
                                                                            const loginForm = document.getElementById('loginForm');
                                                                                if (loginForm) {
                                                                                        loginForm.addEventListener('submit', async (e) => {
                                                                                                    e.preventDefault();
                                                                                                                const username = document.getElementById('username').value.trim();
                                                                                                                            const password = document.getElementById('password').value;
                                                                                                                                        const errorDiv = document.getElementById('login-error');
                                                                                                                                                    errorDiv.classList.add('hidden');

                                                                                                                                                                try {
                                                                                                                                                                                const data = await apiCall('api/auth.php?action=login', 'POST', { username, password });
                                                                                                                                                                                                if (data.status === 'success') {
                                                                                                                                                                                                                    // Redirect based on role
                                                                                                                                                                                                                                        redirectToDashboard(data.role);
                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                            showError(data.message);
                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                        } catch (err) {
                                                                                                                                                                                                                                                                                                                        showError(err.message);
                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                    // Logout button listener (if present)
                                                                                                                                                                                                                                                                                                                                                        const logoutBtn = document.getElementById('logoutBtn');
                                                                                                                                                                                                                                                                                                                                                            if (logoutBtn) {
                                                                                                                                                                                                                                                                                                                                                                    logoutBtn.addEventListener('click', logout);
                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                        function showError(message) {
                                                                                                                                                                                                                                                                                                                                                                            const errorDiv = document.getElementById('login-error');
                                                                                                                                                                                                                                                                                                                                                                                if (errorDiv) {
                                                                                                                                                                                                                                                                                                                                                                                        errorDiv.textContent = message;
                                                                                                                                                                                                                                                                                                                                                                                                errorDiv.classList.remove('hidden');
                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                            alert(message);
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                function redirectToDashboard(role) {
                                                                                                                                                                                                                                                                                                                                                                                                                    switch (role) {
                                                                                                                                                                                                                                                                                                                                                                                                                            case 'admin': window.location.href = 'admin.html'; break;
                                                                                                                                                                                                                                                                                                                                                                                                                                    case 'farmer': window.location.href = 'farmer.html'; break;
                                                                                                                                                                                                                                                                                                                                                                                                                                            case 'mewa': window.location.href = 'mewa.html'; break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                    case 'moc': window.location.href = 'moc.html'; break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                            case 'importer': window.location.href = 'importer.html'; break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    default: window.location.href = 'index.html';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * Check session on page load (to be called in each dashboard)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          async function checkSession() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const data = await apiCall('api/auth.php?action=check');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (data.authenticated) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Optionally update UI with user name
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const userNameSpan = document.getElementById('userName');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (userNameSpan) userNameSpan.textContent = data.full_name;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return data;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Not logged in, redirect to login
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              window.location.href = 'index.html';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.error('Session check failed', err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      window.location.href = 'index.html';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * Logout function (can be called from any page)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    async function logout() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await apiCall('api/auth.php?action=logout', 'POST');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        window.location.href = 'index.html';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    alert('Logout failed');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Expose logout globally for inline onclick handlers
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        window.logout = logout;