<?php
// api/auth.php
require_once 'config.php';

$action = $_GET['action'] ?? '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    switch ($action) {
            case 'login':
                        handleLogin();
                                    break;
                                            case 'logout':
                                                        handleLogout();
                                                                    break;
                                                                            default:
                                                                                        sendJSON(['status' => 'error', 'message' => 'Invalid action'], 400);
                                                                                            }
                                                                                            } elseif ($_SERVER['REQUEST_METHOD'] === 'GET' && $action === 'check') {
                                                                                                handleSessionCheck();
                                                                                                } else {
                                                                                                    sendJSON(['status' => 'error', 'message' => 'Invalid request method'], 405);
                                                                                                    }

                                                                                                    function handleLogin() {
                                                                                                        $data = json_decode(file_get_contents('php://input'), true);
                                                                                                            $username = trim($data['username'] ?? '');
                                                                                                                $password = $data['password'] ?? '';

                                                                                                                    if (!$username || !$password) {
                                                                                                                            sendJSON(['status' => 'error', 'message' => 'Username and password required'], 400);
                                                                                                                                }

                                                                                                                                    try {
                                                                                                                                            $pdo = getDBConnection();
                                                                                                                                                    // Use the correct table name 'user' and columns
                                                                                                                                                            $stmt = $pdo->prepare('SELECT user_id, username, password, role, full_name, status FROM user WHERE username = ?');
                                                                                                                                                                    $stmt->execute([$username]);
                                                                                                                                                                            $user = $stmt->fetch();

                                                                                                                                                                                    if ($user && password_verify($password, $user['password'])) {
                                                                                                                                                                                                if ($user['status'] !== 'active') {
                                                                                                                                                                                                                sendJSON(['status' => 'error', 'message' => 'Account is inactive'], 403);
                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                        session_start();
                                                                                                                                                                                                                                                    session_regenerate_id(true);
                                                                                                                                                                                                                                                                $_SESSION['user_id'] = $user['user_id'];
                                                                                                                                                                                                                                                                            $_SESSION['username'] = $user['username'];
                                                                                                                                                                                                                                                                                        $_SESSION['role'] = $user['role'];
                                                                                                                                                                                                                                                                                                    $_SESSION['full_name'] = $user['full_name'];

                                                                                                                                                                                                                                                                                                                sendJSON([
                                                                                                                                                                                                                                                                                                                                'status' => 'success',
                                                                                                                                                                                                                                                                                                                                                'message' => 'Login successful',
                                                                                                                                                                                                                                                                                                                                                                'role' => $user['role'],
                                                                                                                                                                                                                                                                                                                                                                                'full_name' => $user['full_name']
                                                                                                                                                                                                                                                                                                                                                                                            ]);
                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                sendJSON(['status' => 'error', 'message' => 'Invalid credentials'], 401);
                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (PDOException $e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                    sendJSON(['status' => 'error', 'message' => 'Database error'], 500);
                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                        function handleLogout() {
                                                                                                                                                                                                                                                                                                                                                                                                                                            session_start();
                                                                                                                                                                                                                                                                                                                                                                                                                                                session_unset();
                                                                                                                                                                                                                                                                                                                                                                                                                                                    session_destroy();
                                                                                                                                                                                                                                                                                                                                                                                                                                                        sendJSON(['status' => 'success', 'message' => 'Logged out']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                        function handleSessionCheck() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            session_start();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (isset($_SESSION['user_id'])) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        sendJSON([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'status' => 'success',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'authenticated' => true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'role' => $_SESSION['role'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'full_name' => $_SESSION['full_name']
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            sendJSON([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'status' => 'success',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'authenticated' => false
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ?>