CREATE DATABASE IF NOT EXISTS AgriBalance;
USE AgriBalance;

-- ============================================================
-- 1. USERS
-- ============================================================
CREATE TABLE user (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(50) NOT NULL UNIQUE,
            password VARCHAR(255) NOT NULL,
                role ENUM('admin','mewa','moc','farmer','importer') NOT NULL,
                    full_name VARCHAR(100) NOT NULL,
                        email VARCHAR(100) UNIQUE,
                            phone VARCHAR(20),
                                status ENUM('active','inactive','pending') DEFAULT 'active'
                                );

                                -- ============================================================
                                -- 2. ROLE TABLES
                                -- ============================================================
                                CREATE TABLE farmer (
                                    user_id INT PRIMARY KEY,
                                        region VARCHAR(100) NOT NULL,
                                            farm_size_hectares DECIMAL(10,2) NOT NULL,
                                                FOREIGN KEY (user_id) REFERENCES user(user_id) ON DELETE CASCADE
                                                );

                                                CREATE TABLE importer (
                                                    user_id INT PRIMARY KEY,
                                                        company_name VARCHAR(150) NOT NULL,
                                                            FOREIGN KEY (user_id) REFERENCES user(user_id) ON DELETE CASCADE
                                                            );

                                                            CREATE TABLE mewa_employee (
                                                                user_id INT PRIMARY KEY,
                                                                    region VARCHAR(100) NOT NULL,
                                                                        department VARCHAR(100),
                                                                            FOREIGN KEY (user_id) REFERENCES user(user_id) ON DELETE CASCADE
                                                                            );

                                                                            CREATE TABLE moc_employee (
                                                                                user_id INT PRIMARY KEY,
                                                                                    region VARCHAR(100) NOT NULL,
                                                                                        department VARCHAR(100),
                                                                                            FOREIGN KEY (user_id) REFERENCES user(user_id) ON DELETE CASCADE
                                                                                            );

                                                                                            -- ============================================================
                                                                                            -- 3. CROP
                                                                                            -- ============================================================
                                                                                            CREATE TABLE crop (
                                                                                                crop_id INT AUTO_INCREMENT PRIMARY KEY,
                                                                                                    crop_name VARCHAR(100) NOT NULL UNIQUE,
                                                                                                        growing_season VARCHAR(50) NULL
                                                                                                        );

                                                                                                        -- ============================================================
                                                                                                        -- 4. PRODUCTION FORECAST
                                                                                                        -- ============================================================
                                                                                                        CREATE TABLE production_forecast (
                                                                                                            farmer_id INT NOT NULL,
                                                                                                                crop_id INT NOT NULL,
                                                                                                                    harvest_start_date DATE NOT NULL,
                                                                                                                        harvest_end_date DATE NOT NULL,
                                                                                                                            expected_yield_tons DECIMAL(10,2) NOT NULL,
                                                                                                                                status ENUM('submitted','verified') DEFAULT 'submitted',
                                                                                                                                    PRIMARY KEY (farmer_id, crop_id, harvest_start_date),
                                                                                                                                        FOREIGN KEY (farmer_id) REFERENCES farmer(user_id) ON DELETE CASCADE,
                                                                                                                                            FOREIGN KEY (crop_id) REFERENCES crop(crop_id),
                                                                                                                                                CHECK (harvest_start_date <= harvest_end_date),
                                                                                                                                                    INDEX idx_harvest_range (crop_id, harvest_start_date, harvest_end_date)
                                                                                                                                                    );

                                                                                                                                                    -- ============================================================
                                                                                                                                                    -- 5. IMPORT APPLICATION
                                                                                                                                                    -- ============================================================
                                                                                                                                                    CREATE TABLE import_application (
                                                                                                                                                        importer_id INT NOT NULL,
                                                                                                                                                            crop_id INT NOT NULL,
                                                                                                                                                                arrival_date DATE NOT NULL,
                                                                                                                                                                    requested_quantity_tons DECIMAL(10,2) NOT NULL,
                                                                                                                                                                        status ENUM('pending','approved','rejected','capped') DEFAULT 'pending',
                                                                                                                                                                            approved_quantity DECIMAL(10,2) NULL,
                                                                                                                                                                                notes TEXT,
                                                                                                                                                                                    PRIMARY KEY (importer_id, crop_id, arrival_date),
                                                                                                                                                                                        FOREIGN KEY (importer_id) REFERENCES importer(user_id) ON DELETE CASCADE,
                                                                                                                                                                                            FOREIGN KEY (crop_id) REFERENCES crop(crop_id),
                                                                                                                                                                                                INDEX idx_arrival (crop_id, arrival_date)
                                                                                                                                                                                                );

                                                                                                                                                                                                -- ============================================================
                                                                                                                                                                                                -- 6. MARKET SNAPSHOT (historical)
                                                                                                                                                                                                -- ============================================================
                                                                                                                                                                                                CREATE TABLE market_snapshot (
                                                                                                                                                                                                    snapshot_id INT AUTO_INCREMENT PRIMARY KEY,
                                                                                                                                                                                                        crop_id INT NOT NULL,
                                                                                                                                                                                                            region VARCHAR(100) NOT NULL DEFAULT 'National',  -- 'National' for country‑level
                                                                                                                                                                                                                snapshot_period VARCHAR(7) NOT NULL,               -- 'YYYY-MM'
                                                                                                                                                                                                                    price DECIMAL(10,2) NULL,
                                                                                                                                                                                                                        demand_estimate DECIMAL(10,2) NOT NULL,
                                                                                                                                                                                                                            UNIQUE KEY unique_snapshot (crop_id, region, snapshot_period),
                                                                                                                                                                                                                                FOREIGN KEY (crop_id) REFERENCES crop(crop_id)
                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                -- ============================================================
                                                                                                                                                                                                                                -- 7. MARKET FORECAST (future predictions)
                                                                                                                                                                                                                                -- ============================================================
                                                                                                                                                                                                                                CREATE TABLE market_forecast (
                                                                                                                                                                                                                                    forecast_id INT AUTO_INCREMENT PRIMARY KEY,
                                                                                                                                                                                                                                        crop_id INT NOT NULL,
                                                                                                                                                                                                                                            region VARCHAR(100) NOT NULL DEFAULT 'National',
                                                                                                                                                                                                                                                forecast_period VARCHAR(7) NOT NULL,
                                                                                                                                                                                                                                                    forecast_demand DECIMAL(10,2) NOT NULL,
                                                                                                                                                                                                                                                        UNIQUE KEY unique_forecast (crop_id, region, forecast_period),
                                                                                                                                                                                                                                                            FOREIGN KEY (crop_id) REFERENCES crop(crop_id)
                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                            -- ============================================================
                                                                                                                                                                                                                                                            -- 8. RECOMMENDATION
                                                                                                                                                                                                                                                            -- ============================================================
                                                                                                                                                                                                                                                            CREATE TABLE recommendation (
                                                                                                                                                                                                                                                                recommendation_id INT AUTO_INCREMENT PRIMARY KEY,
                                                                                                                                                                                                                                                                    crop_id INT NOT NULL,
                                                                                                                                                                                                                                                                        farmer_id INT NULL,
                                                                                                                                                                                                                                                                            mewa_id INT NOT NULL,
                                                                                                                                                                                                                                                                                snapshot_id INT NULL,
                                                                                                                                                                                                                                                                                    forecast_id INT NULL,
                                                                                                                                                                                                                                                                                        recommendation_text TEXT NOT NULL,
                                                                                                                                                                                                                                                                                            priority_level ENUM('low','medium','high') DEFAULT 'medium',
                                                                                                                                                                                                                                                                                                is_active BOOLEAN DEFAULT TRUE,
                                                                                                                                                                                                                                                                                                    UNIQUE KEY unique_recommendation (crop_id, farmer_id, mewa_id, snapshot_id, forecast_id),
                                                                                                                                                                                                                                                                                                        FOREIGN KEY (crop_id) REFERENCES crop(crop_id),
                                                                                                                                                                                                                                                                                                            FOREIGN KEY (farmer_id) REFERENCES farmer(user_id) ON DELETE SET NULL,
                                                                                                                                                                                                                                                                                                                FOREIGN KEY (mewa_id) REFERENCES mewa_employee(user_id) ON DELETE CASCADE,
                                                                                                                                                                                                                                                                                                                    FOREIGN KEY (snapshot_id) REFERENCES market_snapshot(snapshot_id) ON DELETE SET NULL,
                                                                                                                                                                                                                                                                                                                        FOREIGN KEY (forecast_id) REFERENCES market_forecast(forecast_id) ON DELETE SET NULL
                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                        -- ============================================================
                                                                                                                                                                                                                                                                                                                        -- DUMMY DATA
                                                                                                                                                                                                                                                                                                                        -- ============================================================

                                                                                                                                                                                                                                                                                                                        -- Crops (Arabic names)
                                                                                                                                                                                                                                                                                                                        INSERT INTO crop (crop_name, growing_season) VALUES
                                                                                                                                                                                                                                                                                                                        ('قمح', 'شتوي'),
                                                                                                                                                                                                                                                                                                                        ('شعير', 'ربيعي'),
                                                                                                                                                                                                                                                                                                                        ('طماطم', 'صيفي'),
                                                                                                                                                                                                                                                                                                                        ('خيار', 'صيفي'),
                                                                                                                                                                                                                                                                                                                        ('بصل', 'شتوي');

                                                                                                                                                                                                                                                                                                                        -- Users (password = 'password')
                                                                                                                                                                                                                                                                                                                        SET @password_hash = '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi';

                                                                                                                                                                                                                                                                                                                        INSERT INTO user (username, password, role, full_name, email, phone, status) VALUES
                                                                                                                                                                                                                                                                                                                        ('admin', @password_hash, 'admin', 'مدير النظام', 'admin@agribalance.sa', '0500000001', 'active'),
                                                                                                                                                                                                                                                                                                                        ('mewa_riyadh', @password_hash, 'mewa', 'أحمد العتيبي', 'a.alotaibi@mewa.gov.sa', '0501111111', 'active'),
                                                                                                                                                                                                                                                                                                                        ('mewa_jeddah', @password_hash, 'mewa', 'فاطمة الزهراني', 'f.alzahrani@mewa.gov.sa', '0502222222', 'active'),
                                                                                                                                                                                                                                                                                                                        ('moc_riyadh', @password_hash, 'moc', 'خالد السليمان', 'k.alsulaiman@moc.gov.sa', '0503333333', 'active'),
                                                                                                                                                                                                                                                                                                                        ('moc_dammam', @password_hash, 'moc', 'نورة القحطاني', 'n.alqahtani@moc.gov.sa', '0504444444', 'active'),
                                                                                                                                                                                                                                                                                                                        ('farmer1', @password_hash, 'farmer', 'سعيد المالكي', 'farmer1@gmail.com', '0551111111', 'active'),
                                                                                                                                                                                                                                                                                                                        ('farmer2', @password_hash, 'farmer', 'عبدالله الشمري', 'farmer2@gmail.com', '0552222222', 'active'),
                                                                                                                                                                                                                                                                                                                        ('importer1', @password_hash, 'importer', 'شركة الرشيد', 'info@alrashed.sa', '0561111111', 'active'),
                                                                                                                                                                                                                                                                                                                        ('importer2', @password_hash, 'importer', 'مؤسسة الجزيرة', 'info@aljazeera.sa', '0562222222', 'active');

                                                                                                                                                                                                                                                                                                                        -- Farmers
                                                                                                                                                                                                                                                                                                                        INSERT INTO farmer (user_id, region, farm_size_hectares) VALUES
                                                                                                                                                                                                                                                                                                                        (6, 'الرياض', 50.0),
                                                                                                                                                                                                                                                                                                                        (7, 'القصيم', 120.5);

                                                                                                                                                                                                                                                                                                                        -- Importers
                                                                                                                                                                                                                                                                                                                        INSERT INTO importer (user_id, company_name) VALUES
                                                                                                                                                                                                                                                                                                                        (8, 'شركة الرشيد للتجارة'),
                                                                                                                                                                                                                                                                                                                        (9, 'مؤسسة الجزيرة للاستيراد');

                                                                                                                                                                                                                                                                                                                        -- MEWA employees
                                                                                                                                                                                                                                                                                                                        INSERT INTO mewa_employee (user_id, region, department) VALUES
                                                                                                                                                                                                                                                                                                                        (2, 'الرياض', 'الإنتاج النباتي'),
                                                                                                                                                                                                                                                                                                                        (3, 'مكة المكرمة', 'شؤون المزارعين');

                                                                                                                                                                                                                                                                                                                        -- MOC employees
                                                                                                                                                                                                                                                                                                                        INSERT INTO moc_employee (user_id, region, department) VALUES
                                                                                                                                                                                                                                                                                                                        (4, 'الرياض', 'تنظيم الاستيراد'),
                                                                                                                                                                                                                                                                                                                        (5, 'المنطقة الشرقية', 'مراقبة الأسواق');

                                                                                                                                                                                                                                                                                                                        -- Production forecasts
                                                                                                                                                                                                                                                                                                                        INSERT INTO production_forecast (farmer_id, crop_id, harvest_start_date, harvest_end_date, expected_yield_tons, status) VALUES
                                                                                                                                                                                                                                                                                                                        (6, 1, '2026-04-01', '2026-04-30', 200.0, 'verified'),  -- قمح
                                                                                                                                                                                                                                                                                                                        (6, 3, '2026-05-15', '2026-06-15', 150.0, 'submitted'), -- طماطم
                                                                                                                                                                                                                                                                                                                        (7, 2, '2026-03-10', '2026-04-10', 300.0, 'verified'),  -- شعير
                                                                                                                                                                                                                                                                                                                        (7, 5, '2026-02-20', '2026-03-20', 80.0, 'submitted');  -- بصل

                                                                                                                                                                                                                                                                                                                        -- Import applications
                                                                                                                                                                                                                                                                                                                        INSERT INTO import_application (importer_id, crop_id, arrival_date, requested_quantity_tons, status, notes) VALUES
                                                                                                                                                                                                                                                                                                                        (8, 3, '2026-05-20', 500.0, 'pending', 'طلب توريد طماطم'),
                                                                                                                                                                                                                                                                                                                        (8, 5, '2026-04-10', 200.0, 'approved', 'تمت الموافقة'),
                                                                                                                                                                                                                                                                                                                        (9, 1, '2026-04-15', 300.0, 'pending', NULL),
                                                                                                                                                                                                                                                                                                                        (9, 4, '2026-06-01', 100.0, 'capped', 'الموافقة بكمية محدودة');

                                                                                                                                                                                                                                                                                                                        -- Market snapshots (region now uses 'National' for country‑level)
                                                                                                                                                                                                                                                                                                                        INSERT INTO market_snapshot (crop_id, region, snapshot_period, price, demand_estimate) VALUES
                                                                                                                                                                                                                                                                                                                        (1, 'National', '2026-01', 1500.00, 5000.0),
                                                                                                                                                                                                                                                                                                                        (1, 'National', '2026-02', 1550.00, 5200.0),
                                                                                                                                                                                                                                                                                                                        (3, 'الرياض', '2026-01', 2000.00, 800.0),
                                                                                                                                                                                                                                                                                                                        (3, 'الرياض', '2026-02', 2100.00, 850.0);

                                                                                                                                                                                                                                                                                                                        -- Market forecasts
                                                                                                                                                                                                                                                                                                                        INSERT INTO market_forecast (crop_id, region, forecast_period, forecast_demand) VALUES
                                                                                                                                                                                                                                                                                                                        (1, 'National', '2026-04', 6000.0),
                                                                                                                                                                                                                                                                                                                        (3, 'الرياض', '2026-05', 900.0),
                                                                                                                                                                                                                                                                                                                        (2, 'القصيم', '2026-03', 400.0);

                                                                                                                                                                                                                                                                                                                        -- Recommendations (using snapshot_id and forecast_id)
                                                                                                                                                                                                                                                                                                                        -- Note: snapshot_id and forecast_id are auto‑incremented; we need to know their values.
                                                                                                                                                                                                                                                                                                                        -- For simplicity, we'll assume they are 1,2,3... based on insertion order.
                                                                                                                                                                                                                                                                                                                        INSERT INTO recommendation (
                                                                                                                                                                                                                                                                                                                            crop_id, farmer_id, mewa_id,
                                                                                                                                                                                                                                                                                                                                snapshot_id, forecast_id,
                                                                                                                                                                                                                                                                                                                                    recommendation_text, priority_level, is_active
                                                                                                                                                                                                                                                                                                                                    ) VALUES (
                                                                                                                                                                                                                                                                                                                                        1, NULL, 2,
                                                                                                                                                                                                                                                                                                                                            1, NULL,
                                                                                                                                                                                                                                                                                                                                                'يوصى بزراعة القمح هذا الموسم نظراً للطلب المتزايد', 'high', TRUE
                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                INSERT INTO recommendation (
                                                                                                                                                                                                                                                                                                                                                    crop_id, farmer_id, mewa_id,
                                                                                                                                                                                                                                                                                                                                                        snapshot_id, forecast_id,
                                                                                                                                                                                                                                                                                                                                                            recommendation_text, priority_level, is_active
                                                                                                                                                                                                                                                                                                                                                            ) VALUES (
                                                                                                                                                                                                                                                                                                                                                                3, 6, 3,
                                                                                                                                                                                                                                                                                                                                                                    NULL, 2,
                                                                                                                                                                                                                                                                                                                                                                        'بناءً على توقعات الطلب العالي في مايو، ننصح بزراعة الطماطم', 'high', TRUE
                                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                        INSERT INTO recommendation (
                                                                                                                                                                                                                                                                                                                                                                            crop_id, farmer_id, mewa_id,
                                                                                                                                                                                                                                                                                                                                                                                snapshot_id, forecast_id,
                                                                                                                                                                                                                                                                                                                                                                                    recommendation_text, priority_level, is_active
                                                                                                                                                                                                                                                                                                                                                                                    ) VALUES (
                                                                                                                                                                                                                                                                                                                                                                                        2, NULL, 2,
                                                                                                                                                                                                                                                                                                                                                                                            NULL, 3,
                                                                                                                                                                                                                                                                                                                                                                                                'الطلب المتوقع على الشعير مرتفع – فرصة جيدة للمزارعين', 'medium', TRUE
                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                ALTER TABLE import_application ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;