// js/farmer.js
document.addEventListener('DOMContentLoaded', async () => {
    const session = await checkSession();
        if (session.authenticated && session.role === 'farmer') {
                document.getElementById('userName').textContent = session.full_name;
                        loadCrops();
                                loadFarmerData();
                                    } else {
                                            window.location.href = 'index.html';
                                                }
                                                    document.getElementById('logoutBtn').addEventListener('click', logout);
                                                    });

                                                    async function loadCrops() {
                                                        const res = await fetch('api/farmer.php?action=crops');
                                                            const data = await res.json();
                                                                if (data.status === 'success') {
                                                                        const select = document.getElementById('cropSelect');
                                                                                select.innerHTML = '<option value="">Select Crop</option>' +
                                                                                            data.crops.map(c => `<option value="${c.crop_id}">${c.crop_name}</option>`).join('');
                                                                                                }
                                                                                                }

                                                                                                async function loadFarmerData() {
                                                                                                    // Load forecasts
                                                                                                        const res = await fetch('api/farmer.php?action=forecasts');
                                                                                                            const data = await res.json();
                                                                                                                if (data.status === 'success') {
                                                                                                                        const tbody = document.querySelector('#forecastsTable tbody');
                                                                                                                                tbody.innerHTML = data.forecasts.map(f => `
                                                                                                                                            <tr>
                                                                                                                                                            <td>${f.crop_name}</td>
                                                                                                                                                                            <td>${f.expected_yield_tons}</td>
                                                                                                                                                                                            <td>${f.harvest_start_date}</td>
                                                                                                                                                                                                            <td>${f.harvest_end_date}</td>
                                                                                                                                                                                                                            <td><span class="badge badge-info">${f.status}</span></td>
                                                                                                                                                                                                                                        </tr>
                                                                                                                                                                                                                                                `).join('');

                                                                                                                                                                                                                                                        // Stats
                                                                                                                                                                                                                                                                const activeCrops = new Set(data.forecasts.map(f => f.crop_id)).size;
                                                                                                                                                                                                                                                                        const totalYield = data.forecasts.reduce((sum, f) => sum + parseFloat(f.expected_yield_tons), 0);
                                                                                                                                                                                                                                                                                document.getElementById('activeCrops').textContent = activeCrops;
                                                                                                                                                                                                                                                                                        document.getElementById('totalYield').textContent = totalYield.toFixed(1);
                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                // Load recommendations
                                                                                                                                                                                                                                                                                                    const recRes = await fetch('api/farmer.php?action=recommendations');
                                                                                                                                                                                                                                                                                                        const recData = await recRes.json();
                                                                                                                                                                                                                                                                                                            if (recData.status === 'success') {
                                                                                                                                                                                                                                                                                                                    const container = document.getElementById('recommendationsList');
                                                                                                                                                                                                                                                                                                                            container.innerHTML = recData.recommendations.map(r => `
                                                                                                                                                                                                                                                                                                                                        <div class="glass-card" style="margin-bottom:0.5rem; padding:1rem;">
                                                                                                                                                                                                                                                                                                                                                        <strong>${r.crop_name}</strong> (${r.priority} priority)<br>
                                                                                                                                                                                                                                                                                                                                                                        ${r.recommendation_text}
                                                                                                                                                                                                                                                                                                                                                                                        ${r.farmer_id ? '<br><small>Personalized for you</small>' : '<br><small>General recommendation</small>'}
                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                            `).join('');
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                function openForecastModal() {
                                                                                                                                                                                                                                                                                                                                                                                                                    document.getElementById('forecastModal').classList.remove('hidden');
                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                    function closeForecastModal() {
                                                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById('forecastModal').classList.add('hidden');
                                                                                                                                                                                                                                                                                                                                                                                                                            document.getElementById('forecastForm').reset();
                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                            document.getElementById('forecastForm').addEventListener('submit', async (e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                e.preventDefault();
                                                                                                                                                                                                                                                                                                                                                                                                                                    const formData = new FormData(e.target);
                                                                                                                                                                                                                                                                                                                                                                                                                                        const data = Object.fromEntries(formData);
                                                                                                                                                                                                                                                                                                                                                                                                                                            const res = await fetch('api/farmer.php?action=submit_forecast', {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    method: 'POST',
                                                                                                                                                                                                                                                                                                                                                                                                                                                            headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    body: JSON.stringify(data)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const result = await res.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (result.status === 'success') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        closeForecastModal();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                loadFarmerData();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            alert(result.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });