<?php
// api/importer.php
require_once 'config.php';
requireAuth();
requireRole(['importer', 'admin']); // admin can view for testing

$action = $_GET['action'] ?? '';

if ($_SERVER['REQUEST_METHOD'] === 'GET') {
    switch ($action) {
            case 'profile':
                        getProfile();
                                    break;
                                            case 'applications':
                                                        getApplications();
                                                                    break;
                                                                            case 'crops':          // FIX: Added crops endpoint for importers
                                                                                        listCrops();
                                                                                                    break;
                                                                                                            default:
                                                                                                                        sendJSON(['status' => 'error', 'message' => 'Invalid action'], 400);
                                                                                                                            }
                                                                                                                            } elseif ($_SERVER['REQUEST_METHOD'] === 'POST') {
                                                                                                                                if ($action === 'submit_application') {
                                                                                                                                        submitApplication();
                                                                                                                                            } else {
                                                                                                                                                    sendJSON(['status' => 'error', 'message' => 'Invalid action'], 400);
                                                                                                                                                        }
                                                                                                                                                        } else {
                                                                                                                                                            sendJSON(['status' => 'error', 'message' => 'Method not allowed'], 405);
                                                                                                                                                            }

                                                                                                                                                            // FIX: Added listCrops function specifically for importers
                                                                                                                                                            function listCrops() {
                                                                                                                                                                $pdo = getDBConnection();
                                                                                                                                                                    $stmt = $pdo->query("SELECT crop_id, crop_name FROM crop ORDER BY crop_name");
                                                                                                                                                                        $crops = $stmt->fetchAll();
                                                                                                                                                                            sendJSON(['status' => 'success', 'crops' => $crops]);
                                                                                                                                                                            }

                                                                                                                                                                            function getProfile() {
                                                                                                                                                                                $userId = $_SESSION['user_id'];
                                                                                                                                                                                    $pdo = getDBConnection();
                                                                                                                                                                                        $stmt = $pdo->prepare("
                                                                                                                                                                                                SELECT u.full_name, u.email, u.phone, i.company_name
                                                                                                                                                                                                        FROM user u
                                                                                                                                                                                                                JOIN importer i ON u.user_id = i.user_id
                                                                                                                                                                                                                        WHERE u.user_id = ?
                                                                                                                                                                                                                            ");
                                                                                                                                                                                                                                $stmt->execute([$userId]);
                                                                                                                                                                                                                                    $profile = $stmt->fetch();
                                                                                                                                                                                                                                        if ($profile) {
                                                                                                                                                                                                                                                sendJSON(['status' => 'success', 'profile' => $profile]);
                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                            sendJSON(['status' => 'error', 'message' => 'Profile not found'], 404);
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                function getApplications() {
                                                                                                                                                                                                                                                                    $userId = $_SESSION['user_id'];
                                                                                                                                                                                                                                                                        $pdo = getDBConnection();
                                                                                                                                                                                                                                                                            $stmt = $pdo->prepare("
                                                                                                                                                                                                                                                                                    SELECT ia.*, c.crop_name
                                                                                                                                                                                                                                                                                            FROM import_application ia
                                                                                                                                                                                                                                                                                                    JOIN crop c ON ia.crop_id = c.crop_id
                                                                                                                                                                                                                                                                                                            WHERE ia.importer_id = ?
                                                                                                                                                                                                                                                                                                                    ORDER BY ia.arrival_date DESC
                                                                                                                                                                                                                                                                                                                        ");
                                                                                                                                                                                                                                                                                                                            $stmt->execute([$userId]);
                                                                                                                                                                                                                                                                                                                                $apps = $stmt->fetchAll();
                                                                                                                                                                                                                                                                                                                                    sendJSON(['status' => 'success', 'applications' => $apps]);
                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                    function submitApplication() {
                                                                                                                                                                                                                                                                                                                                        $data = json_decode(file_get_contents('php://input'), true);
                                                                                                                                                                                                                                                                                                                                            $importerId = $_SESSION['user_id'];
                                                                                                                                                                                                                                                                                                                                                $cropId = $data['crop_id'] ?? 0;
                                                                                                                                                                                                                                                                                                                                                    $qty = $data['requested_quantity_tons'] ?? 0;
                                                                                                                                                                                                                                                                                                                                                        $arrival = $data['arrival_date'] ?? '';
                                                                                                                                                                                                                                                                                                                                                            $notes = $data['notes'] ?? '';

                                                                                                                                                                                                                                                                                                                                                                if (!$cropId || !$qty || !$arrival) {
                                                                                                                                                                                                                                                                                                                                                                        sendJSON(['status' => 'error', 'message' => 'Crop, quantity, and arrival date required'], 400);
                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                $pdo = getDBConnection();
                                                                                                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                                                                                            $stmt = $pdo->prepare("
                                                                                                                                                                                                                                                                                                                                                                                                        INSERT INTO import_application (importer_id, crop_id, requested_quantity_tons, arrival_date, notes)
                                                                                                                                                                                                                                                                                                                                                                                                                    VALUES (?, ?, ?, ?, ?)
                                                                                                                                                                                                                                                                                                                                                                                                                            ");
                                                                                                                                                                                                                                                                                                                                                                                                                                    $stmt->execute([$importerId, $cropId, $qty, $arrival, $notes]);
                                                                                                                                                                                                                                                                                                                                                                                                                                            sendJSON(['status' => 'success', 'message' => 'Application submitted']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (PDOException $e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        sendJSON(['status' => 'error', 'message' => 'Database error'], 500);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ?>